name: Setup nodejs and install the dependancies
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
        with: 
          node-version: 18
          cache: 'npm'
    - name: install npm packages
        run: |
          npm install
