name: Build Documentation Website
permissions:   
  contents: write
  packages: read
on:
  push:
    branches:
      - docs
      - main
    paths:
      - .github/workflows/build-docs.yml
      - website/**
  pull_request:
    branches:
      - main
jobs:
  build-docs:
    name: Building Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: docs
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install And Build
        working-directory: website
        run: |
          npm install
          npm run build
      - name: Checkout From gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          force_orphan: true
          allow_empty_commit: true
          
  deploy:
    runs-on: ubuntu-latest
    environment:      
        name: github-pages
        url: ${{ steps.deploy.outputs.page_url }}
    needs: [build-docs]
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deployment To Pages
        uses: actions/deploy-pages@v2
        id: deploy


