name: Run Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore: 
     - docs
     - github-action-setup
  workflow_dispatch:
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-plugin
    - name: testing using jest
      run: npm test
