name: Run Tests
on:
  push:
    branches-ignore: 
     - docs
     - github-action-setup
  workflow_dispatch:
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/setup-plugin
    - name: testing using jest
      run: npm test
