name: Run Tests
on:
  push:
    branches-ignore: 
     - docs
     - github-action-setup
  workflow_dispatch: 
  workflow_call:
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
          cache: 'npm'
      - name: install npm packages
        run: |
          npm install
          npm test
