name: Publish To NPM
on:
  push:
  workflow_dispatch:
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: phips28/gh-action-bump-version@v9.1.0
        with:
          version-type: patch
      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true
          
          
    
